apiVersion: v1
kind: Service
metadata:
  name: words-web-svc
  labels:
    app: words-web
spec:
  ports:
    - port: 80
      targetPort: 80
      name: words-web
  selector:
    app: words-web
  type: LoadBalancer
